CREATE TYPE priority_type AS ENUM ('Low', 'Medium', 'High', 'Urgent');
CREATE TYPE status_type AS ENUM ('New', 'In Progress', 'Closed', 'On Hold');

CREATE TABLE projects (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_name TEXT NOT NULL UNIQUE,
  description TEXT,
  dateadded TIMESTAMP NOT NULL,
  duedate TIMESTAMP,
  dateclosed TIMESTAMP,
  priority priority_type NOT NULL,
  status status_type NOT NULL,
  companyid INTEGER REFERENCES company(id) ON DELETE CASCADE
);
